### ISSUE TITLE
Rep VM Unhealthy External problems

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/rep#11]
Hi Diego,

We had an interesting issue yesterday in production.  We had a problem where 3 of our cells had issues with DNS.   They could not resolve the DNS to our object store.   We believe this was an issue  with the physical host that the VMs were running on as it was only 3 of our over 300 cells that were effected.   The "bad" part was the VMs could still successfully create containers, and could successfully communicate to consul and BBS so the rep thought that the cell was fine.

In fact every staging request to the cell failed due to not being able to download any blobs from the object store.

We observed that the bosh director was also having issues communicating to the bosh-agent and so using the bosh cli it appeared that those cells were "unresponsive".

The major issue we had was there were many staging requests going to these 3 cells (not sure why they were basically winning most staging request auctions).   The task failure metrics we implemented was showing lots of failures on these cells.

We are writing this issue to know if there is anything that could be done from a Diego perspective to help in this situation.   We know there are many things we would like to check as far as cell health and DNS or network issues to particular endpoints are additional external things that we would like to check.

One of our thoughts was to implement a job on the rep that can be configured to "check" things like DNS resolution.  Connectivity to certain important endpoints etc and then somehow communicate to the rep to mark it as unhealthy so that it will no longer participate in auctions.  We know there is the evacuate endpoint we could call (or call the drain script directly).  But is there more health checks the rep is looking to implement?  For instance, keeping track of failed tasks in the last X minutes and have thresholds for marking the cell as unhealthy.

We wanted to get your feedback on possible solutions prior to starting to implement something on our end.

Thanks,

Andrew Edgar

**Comment by andrew-edgar** [comment]
We have had lots of discussion here recently about the rep determining if it's unhealthy for other reasons.   In our current use case.  We have a constant failure to lookup the DNS record for the object store.  Hence every staging request to a particular cell will fail.

Unfortunately everything else in the cell looks good :).   Except for the fact that it can't stage anything.  It also seems perfectly happy to keep picking up staging tasks in the auction.

We would love to discuss your thoughts on how we should mitigate issues like this.  As the rep can see all of these tasks failing (due to the DNS issue).   A back off from participating in tasks might be reasonable in this case.  But of course the concern is when does he thing he's healthy again?

Thanks,

Andrew Edgar

**Comment by ematpl** [comment]
Hi, @andrew-edgar,

I think in general it would be beneficial for cells to advertise a certain amount of their historical behavior with respect to Tasks and LRPs, such as success and failure rate and the duration of time it took for an instance to become healthy. The auctioneer could then back off of cells that had higher recent failure rates or were slow at performing work relative to their peers. I would be concerned about applying any absolute cut-off for fear of a DoS attack via intentionally failing tasks, but something like an exponential back-off could work all right if we can specify the behavior in the correct balance with the other factors in the auction placement score. It would also be important for older history to decay in importance over time or eventually even to disappear completely so as not to disadvantage cells that had a period of trouble permanently.

Thanks,
Eric

**Comment by heyjcollins** [comment]
I'm going to close out this issue as it's unlikely we'll take this on.
