### ISSUE TITLE
Too many container need destory, however, this parameter (diego.executor.garden_healthcheck.timeout) setting is too large to be unreasonable?

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/rep#23]
Hi,:

Recently, I had a problem that only happens when I redeploy pivotal cloud foundry.

the diego.executor.garden_healthcheck.timeout is 600, but we have about 50 containers need destoryed,  It takes too much time, and cause the post-start.sh failed. For us, this has been a long time, is there have some better suggestions to solve this problem?

Version:
PAS 2.1.6

Thanks.

**Comment by emalm** [comment]
Hi, @wdxxs2z,

Since you're using PCF, please open a support ticket with Pivotal to get assistance in resolving this issue.

Thanks,
Eric, CF Diego PM
