### ISSUE TITLE
When the server certificate is a cert chain, the rep does not decode it properly

### ISSUE THREAD

**Issue by athornton2012** [cloudfoundry/rep#24]
`pem.Decode` will only find the next pem block in the byte array, so if the server cert contains multiple pem blocks, this will error with `asn1: structure error: tags don't match`

https://github.com/cloudfoundry/rep/blob/69da58fe3071bd4a20384df6e28f400d3b7fb547/cmd/rep/main.go#L473

**Comment by Amit-PivotalLabs** [comment]
@emalm looks like this issue has been resolved and shipped in v2.16.0, should this issue be closed?

**Comment by emalm** [comment]
Thanks for catching that, @Amit-PivotalLabs !
