### ISSUE TITLE
Cache size blowing out over limit

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/rep#27]
We had a diego cell effectively fail today due to running our of temporary space.

We noted that `du -sh` reported `48GB` for `/var/vcap/data/rep/shared/garden/download_cache`, even though default max cache size was set to just under `10GB`.

We cleared the error by recreating that cell.

Looking at the underlying code, I think this function is meant to keep the used space low: https://github.com/cloudfoundry/cacheddownloader/blob/master/file_cache.go#L378

If I'm understanding that code correctly, it seems to only be tracking items added to the cache since the job started. If the job restarted for any reason, would it incorrectly assume the current size of the cache is `0`, even though there may be many files already on disk?

**Comment by emalm** [comment]
Hey, @aeijdenberg,

As a result of the work we did in https://www.pivotaltracker.com/n/projects/1003146/stories/111783048 (circa [Diego v0.1482.0](https://github.com/cloudfoundry/diego-release/releases/tag/v0.1482.0)), the cached-downloader in the cell rep should track the assets in its cache across restarts. It does so by serializing the in-memory cache to disk in a `saved_cache.json` file in the cache directory and, if present, de-serializing that back into memory on startup. It should also remove any files or directories in the cache directory for which it does not have a file entry in the newly restored in-memory cache. In the case of an abrupt crash and subsequent monit-initiated restart, the rep will find no serialized cache record and will consequently delete everything in the cache directory.

That said, we have over the years occasionally observed and then done our best to squash cache-leak bugs, so I'd be interested to know whether that's happening here, too. Do you currently have other Diego cells in your environments with a download-cache size consistently above that 10GB limit? If so, it might work to stop that cell gracefully and compare the entries in the serialized cache file to the actual files and directories there. The following command worked for me from within the download-cache directory:

```
# cache-file entries
diego-cell/2129ffd5-c544-4d18-b3ed-790b48c61d44:/var/vcap/data/rep/shared/garden/download_cache# cat saved_cache.json | jq --arg pwd "$PWD/" '.Entries | to_entries[] | .value | (.ExpandedDirectoryPath | select(. != "")) // .FilePath | ltrimstr($pwd)' -r
0ace2355234e2cd4d21ff12d1997138c-1545243328344063414-2
6942123d3462ad9d21a45729c3cae183-1545243311654108211-1.d

# diff with directory contents
diego-cell/2129ffd5-c544-4d18-b3ed-790b48c61d44:/var/vcap/data/rep/shared/garden/download_cache# diff -u <(cat saved_cache.json | jq --arg pwd "$PWD/" '.Entries | to_entries[] | .value | (.ExpandedDirectoryPath | select(. != "")) // .FilePath | ltrimstr($pwd)' -r) <(ls -1 | grep -v -E '^(temp|saved_cache.json)$')

# discrepancy iff nonzero
diego-cell/2129ffd5-c544-4d18-b3ed-790b48c61d44:/var/vcap/data/rep/shared/garden/download_cache# echo $?
0
```

Also, what was the impact you noticed from this failed cell on the availability of previously running apps or on CF app operations such as `cf push` or `cf run-task`?

Thanks,
Eric

**Comment by aeijdenberg** [comment]
Hi @emalm ,

I'll take a look at that file if it re-occurs. A quick test earlier showed all our other diego cells were showing usage as expected and I've recreated that cell now so no longer have that file to check.

We observed the issue as we have a Concourse job that deploys a new version of an app every 5 minutes as a healthcheck and that started failing around 6:00am today. It then kept failing every 5 minutes as I guess it must have kept hitting the same diego-cell.

```
Renaming app cf-healthcheck to cf-healthcheck-venerable in org system / space cf-healthcheck as ci-system-cf-healthcheck...
OK
Using manifest file /tmp/build/put/manifest/manifest.yml

Creating app cf-healthcheck in org system / space cf-healthcheck as ci-system-cf-healthcheck...
OK

Using route cf-healthcheck.system.y.cld.gov.au
Binding cf-healthcheck.system.y.cld.gov.au to cf-healthcheck...
OK

Using route cf-healthcheck.y.cld.gov.auDownloading app package...

Binding cf-healthcheck.y.cld.gov.au to cf-healthcheck...
OK

Uploading cf-healthcheck...
Uploading app files from: /tmp/build/put/build
Uploading 2.3M, 2 files
Done uploading               
OK

Starting app cf-healthcheck in org system / space cf-healthcheck as ci-system-cf-healthcheck...
2018-12-19T18:01:02.97+0000 [API/0]      OUT Creating build for app with guid 24fe8b40-963a-42f8-925a-219313bbe438
2018-12-19T18:01:04.96+0000 [API/0]      OUT Updated app with guid 24fe8b40-963a-42f8-925a-219313bbe438 ({"state"=>"STARTED"})
Downloading binary_buildpack...
Downloaded binary_buildpack
Cell ceedf0f8-d3c2-41aa-9ddf-71989413fb78 creating container for instance e7b0b571-9d96-47d0-bdfe-ef591f2f6b10
Cell ceedf0f8-d3c2-41aa-9ddf-71989413fb78 successfully created container for instance e7b0b571-9d96-47d0-bdfe-ef591f2f6b10
Downloading app package...
Downloading app package failed
Cell ceedf0f8-d3c2-41aa-9ddf-71989413fb78 stopping instance e7b0b571-9d96-47d0-bdfe-ef591f2f6b10
Cell ceedf0f8-d3c2-41aa-9ddf-71989413fb78 destroying container for instance e7b0b571-9d96-47d0-bdfe-ef591f2f6b10
Cell ceedf0f8-d3c2-41aa-9ddf-71989413fb78 successfully destroyed container for instance e7b0b571-9d96-47d0-bdfe-ef591f2f6b10

Deleting app cf-healthcheck in org system / space cf-healthcheck as ci-system-cf-healthcheck...
OK
Renaming app cf-healthcheck-venerable to cf-healthcheck in org system / space cf-healthcheck as ci-system-cf-healthcheck...
OK
error: StagingError

TIP: use 'cf logs cf-healthcheck --recent' for more information
error running command: exit status 1
```

We were able to identify the issue quickly as we had seen an AlertManager alert start firing at 7pm last night that we'd decided to ignore:

```
[FIRING:2]  (BOSHJobEphemeralDiskFull cf 5 diego-cell main y-cld-gov-au bosh-job critical)
BOSH Job `y-cld-gov-au/main/cf/diego-cell/5` has used more than 80% of its ephemeral disk for 30ms: 81%
```

I'll keep an eye across our fleet and see if we can reproduce.

So far as I can tell it was just pushing new apps that was affected (and `bosh` regarded the instance as healthy). I don't know if other apps other than this was affected as we caught it out of hours and recreated it before any of our regular users would be pushing new apps.

**Comment by heyjcollins** [comment]
As this issue's been idle for quite a long time, I'm going to go ahead and close out this issue.

**Comment by ansergit** [comment]
hi @heyjcollins 

IHAC still waiting for a permanent fix in the code. We observed this in diego-release 2.22.8.
We may be able to reproduce this by somehow making the buildpack fail checksum and try to download again and again..
```
{"timestamp":"1552428554.802373409","source":"rep","message":"rep.executing-container-operation.task-processor.run-container.containerstore-create.node-create.failed-fetching-cache-dependency","log_level":2,"data":{"cache-key":"012ac53f-2080-4404-af29-5556a71517f2_dfe277ba0fef861fada0aa9ff67f95dfc2ba3cee88cdcffe82bae6441a8cbe88","container-guid":"f99527fd-be93-4947-8280-2dba8793a694","container-state":"reserved","download-url":"https://blobstore.service.cf.internal:4443/read/cc-buildpacks/01/2a/012ac53f-2080-4404-af29-5556a71517f2_dfe277ba0fef861fada0aa9ff67f95dfc2ba3cee88cdcffe82bae6441a8cbe88?md5=2Vq44hQ7ATqdd0jvcsjvaw\u0026expires=1552432141","error":"zip: checksum error","guid":"f99527fd-be93-4947-8280-2dba8793a694","session":"3481.1.3.2.1"}}
```
so, we end up with a growing download-cache directory and unable to clean makes it run out of disk space.
